#2813: modified context file to set Entity at project level
mbrainerd/tk-core pull request #37
Opened 2019-12-27 12:20 UTC by ssreeram-DD

2019-12-27 17:38 UTC, mbrainerd requested changes
Rejected. This is too broad of an assumption. I'm actually not sure why this change is even needed. The only time we need to worry about `Project` being in the `entity` field is when the primary entity is a `Task`. In which case, down in the `build_entity_dict` machinery, it should be querying the `entity` field on the `Task` entity in Shotgun and populating this for you.

Please alliterate your issue so we can best determine how to resolve.

2020-01-06 12:44 UTC, aparna-d2 commented
Copying over the relevant comments from http://shotgun.d2-india.com/detail/Ticket/2813:
- Shotgun context is updating on Creating New File to editorial, HIRANYA.
- But on re-opening file at project level, shotgun context is not updating to editorial, HIRANYA and is instead updated to just HIRANYA (project, no task)
- We found that context is being set to task, but is getting switched back to project (with no task).
- On checking the calling method, we found engine._on_project_load_callback() (enabled by automatic_context_change) is causing this.
- The relevant code is (lines 859-869):
```
            tk = tank.tank_from_path(script_path)

            # Extract a new context based on the file and change to that
            # context.
            new_context = tk.context_from_path(
                script_path,
                previous_context=self.context,
            )

            if new_context != self.context:
                tank.platform.change_context(new_context)
```
- We expect the context to be same (since we have a `sync_task_and_step()` in context.py), but the created context from path does not contain an entity, whereas in parent context, project is present in both project and entity fields, and `sync_task_and_step()` (from parent context) only happens if there is an entity present.

2020-01-06 18:55 UTC, mbrainerd commented
Try this instead:

```
    def sync_task_and_step(self, other):
        """
        Syncs the current context's task and step with another context.

        This method only sets the task and step if the contexts' entities and
        additional_entities lists match, and only if the current context's task
        and step, respectively, are not already set.
        """
        if not other.entity:
            return

        # Compare with this context's entity if defined or the project if not
        if other.entity in (self.__entity, self.__project) and \
           other.additional_entities == self.__additional_entities:

            # Handle the case where the project is the task's parent entity
            if not self.__entity:
                self.__entity = other.entity

            # Handle edge case where the context has a task but no step
            if not self.__step:
                self.__step = other.step

            # Assign the previous task if the step matches
            if not self.__task and self.__step == other.step:
                self.__task = other.task
```

2020-01-07 15:33 UTC, mbrainerd approved these changes

2020-01-20 13:45 UTC, merged