Updated deserialize to use existing tank object
mbrainerd/tk-core pull request #39
Opened 2020-01-09 04:32 UTC by jroy1992

2020-01-09 18:40 UTC, mbrainerd commented on python/tank/context.py
> +    def deserialize(cls, context_str, tank=None):
Please use `tk` as the named parameter to match the module convention.

2020-01-09 18:41 UTC, mbrainerd requested changes
See inline comment

2020-01-10 04:32 UTC, jroy1992 commented
Addressed comment.

2020-01-10 06:12 UTC, mbrainerd approved these changes

2020-01-10 12:03 UTC, merged